multipath-tools tests: use assert_true/false instead of assert()
Otherwise the build fails with userspace-rcu 0.14 with

   error: implicit declaration of function 'assert' [-Werror=implicit-function-declaration]
   note: 'assert' is defined in header '<assert.h>'; did you forget to '#include <assert.h>'?

Until liburcu 0.13.0, this didn't show up as a compile error, because
"assert.h" was pulled in via config.h -> urcu.h.

But these assert() calls should have been cmocka assert macros
in the first place.

Signed-off-by: Dirk Müller <dirk@dmllr.de>
Signed-off-by: Martin Wilck <mwilck@suse.com>